SELECT 
    a."_ROW" AS investment_key
    ,a."DATE" AS investment_date
    ,a."ADDED_INVESTMENT" as value
    ,a."TOTAL" AS total
    ,b."TRANSACTION_TYPE"
    ,c."DATE_KEY" 
FROM "FIVETRAN_DATABASE"."GOOGLE_SHEETS"."GOOGLE_SHEETS" a
LEFT JOIN "FIVETRAN_DATABASE"."DROPBOX"."TRANSACTION_TYPE" b
    ON a."SOURCE" = b."TRANSATION_SOURCE"
LEFT JOIN "FIVETRAN_DATABASE"."DROPBOX"."DATE" c
    ON a."DATE" = c."FULL_DATE"